sudo: required
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.7.0.2
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.8.0.0
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.8.1.0
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.9.0.1
env:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.8.0.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
script:
  - composer require aoepeople/composer-installers:*
  - composer install --dev
  - phpunit --bootstrap=test/bootstrap.php test
  - .travis/setup.sh
  - .travis/build.sh
deploy:
  provider: releases
  api_key:
    secure: r5HmWfpDi17JJVEfcAjmkpQH9McW9O0UoBzPS76EduXb8SPjMgEiI2eRoZuQxkjBn2GxKn07gTvkhKT27YWOQSzzrvfHJjJtPajpxLlCX9pmUqDP+lIJ/4273mv+urhCyIrAAGpMMeChmKdXMHOCaSvbKyP7TwsCUYQQnqw8gXK9je4T0xUOg9KahA7ENYVnBasshvFsUAhe7pLXU57DqwNaKkZq/K8B0mCAc33rEaKbUc0yjS6D0S4vA7I1tKfAATdKxbrOlYYFtSDOijhnYeGeJsWRw09E7JIYsDIRgV+nv+nKDLYAnSum1TmQtTVGh3jVNKVHoV4LRjp4QG+BnI5LwEcRrYPp8MMmwTepNnOH4Zlyngh35D8GcDTasmOOr4nicGbaf4HhErj+EJcBJfsMPhjtsmhQugC0zJXqYlB+QA3tgL5rgLBwkACizvdZonqiYZwydQgSMJHftDdFdxQH41b+IvYun1fCZ+HVOiFBGzz8U8DF/ZnTSE46geUB4uptDfFBBa9g8RTZD1d/MnIst8devBXvCwmNzuMgnKsOLyqg+c/E7ZA4IvQSnIRxfJSUVmq26BZC2B86V9jh2kSiYwpEPS9c0T4apZ8kRm6rJC91n6NknvE81B+ZUkCc7RLLoOp6pys/Xh/dHu4Kqehs7Bcbe0esKwEbIpZJeqc=
  file:
    - "hackathon-derivedattributes.zip"
    - "hackathon-derivedattributes.tar.gz"
  skip_cleanup: true
  on:
    tags: true