sudo: required
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.7.0.2
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.8.0.0
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.8.1.0
    - php: 5.6
      env: MAGENTO_VERSION=magento-ce-1.9.0.1
env:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.8.0.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
script:
  - composer install --dev
  - phpunit --bootstrap=test/bootstrap.php test
  - curl -sSL https://raw.githubusercontent.com/schmengler/MageTestStand/master/setup.sh | bash
